export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCESS = 'FETCH_USER_INFO_SUCESS';
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL';
export const FETCH_TODO =  'FETCH_TODO';